# Laptop profile: add laptop-only sources.
$RepoRoot = $HOME/projects/github/scripts/jakoolithyprl
source = $RepoRoot/laptop/UserConfigs/Laptops.conf
source = $RepoRoot/laptop/UserConfigs/LaptopDisplay.conf
