# Laptop profile: add laptop-only sources.
$RepoRoot = /home/zack/projects/scripts/jakoolithyprl
source = $RepoRoot/laptop/UserConfigs/Laptops.conf
source = $RepoRoot/laptop/UserConfigs/LaptopDisplay.conf
