# Laptop profile: add laptop-only sources.
$RepoRoot = /home/zack/projects/scripts/jakoolithyprl
source = $RepoRoot/common/UserConfigs/Laptops.conf
source = $RepoRoot/common/UserConfigs/LaptopDisplay.conf
